name: view_model_test
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  mockito: 5.4.2
  mocktail: 1.0.1
  
  view_model:
    path: ../view_model

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.3
  build_runner: 2.4.6

flutter:
  uses-material-design: true