name: Test

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

on:
  push:
    branches: [main]
    paths-ignore:
      - "**.md"
      - ".git/"
      - "**/.vscode/"
      - "**/.idea/"

jobs:
  build:
    name: Test project
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.13.6"
          channel: "stable"
          cache: true
      - name: Install dependencies
        run: flutter clean && flutter pub get
      - name: Run unit tests
        run: flutter test
